2017-05-16 15:47:45,125 - INFO - [Elapsed time: 0.00] Creating history 8818
2017-05-16 15:47:45,210 - INFO - [Elapsed time: 0.08] 964b37715ec9bd22
2017-05-16 15:47:45,210 - INFO - [Elapsed time: 0.09] Uploading files to galaxy...
2017-05-16 15:47:45,210 - INFO - [Elapsed time: 0.09] Finding files on the NAS...
2017-05-16 15:47:46,920 - INFO - [Elapsed time: 1.80] Uploading files from the NAS...
2017-05-16 15:47:46,920 - INFO - [Elapsed time: 1.80] 1 of 3: Uploading /mnt/nas/External_MiSeq_Backup/GTA/170505/2017-GTA-0058_S15_L001_R1_001.fastq.gz
2017-05-16 15:47:56,692 - INFO - [Elapsed time: 11.57] 2 of 3: Uploading /mnt/nas/External_MiSeq_Backup/GTA/170505/2017-GTA-0058_S15_L001_R2_001.fastq.gz
2017-05-16 15:48:13,113 - INFO - [Elapsed time: 27.99] 3 of 3: Uploading /mnt/nas/External_WGSspades/GTA/170505_Assembled/BestAssemblies/2017-GTA-0058.fasta
2017-05-16 15:48:13,638 - INFO - [Elapsed time: 28.51] Waiting for files to finish uploading...
2017-05-16 15:48:53,949 - INFO - [Elapsed time: 68.82] Finished uploading...
2017-05-16 15:48:53,950 - INFO - [Elapsed time: 68.82] Building list of dataset pairs...
2017-05-16 15:48:54,121 - INFO - [Elapsed time: 69.00] Starting workflow...
2017-05-16 15:49:04,397 - INFO - [Elapsed time: 79.27] Waiting for workflow to finish.
2017-05-16 15:59:08,618 - INFO - [Elapsed time: 683.49] Still waiting for workflow to finish.
2017-05-16 16:09:22,213 - INFO - [Elapsed time: 1297.09] Still waiting for workflow to finish.
2017-05-16 16:19:35,468 - INFO - [Elapsed time: 1910.34] Still waiting for workflow to finish.
2017-05-16 16:26:07,488 - INFO - [Elapsed time: 2302.36] Workflow finished, downloading files...
2017-05-16 16:26:07,488 - INFO - [Elapsed time: 2302.36] Creating directory 8818.
2017-05-16 16:26:07,489 - INFO - [Elapsed time: 2302.36] Downloading files:
2017-05-16 16:26:07,571 - INFO - [Elapsed time: 2302.45]     Downloading snvTable.tsv to /home/devon/PycharmProjects/auto-SNVPhyl/results/8818/snvTable.tsv
2017-05-16 16:26:07,927 - INFO - [Elapsed time: 2302.80]     Downloading vcf2core.tsv to /home/devon/PycharmProjects/auto-SNVPhyl/results/8818/vcf2core.tsv
2017-05-16 16:26:08,262 - INFO - [Elapsed time: 2303.14]     Downloading snvAlignment.phy to /home/devon/PycharmProjects/auto-SNVPhyl/results/8818/snvAlignment.phy
2017-05-16 16:26:08,559 - INFO - [Elapsed time: 2303.43]     Downloading filterStats.txt to /home/devon/PycharmProjects/auto-SNVPhyl/results/8818/filterStats.txt
2017-05-16 16:26:08,868 - INFO - [Elapsed time: 2303.74]     Downloading phylogeneticTree.newick to /home/devon/PycharmProjects/auto-SNVPhyl/results/8818/phylogeneticTree.newick
2017-05-16 16:26:09,132 - INFO - [Elapsed time: 2304.01] [Error Dump]
Traceback (most recent call last):
  File "/home/devon/PycharmProjects/auto-SNVPhyl/main.py", line 41, in run
    return self.main()  # Return the path to the results zip
  File "/home/devon/PycharmProjects/auto-SNVPhyl/main.py", line 173, in main
    wait_for_completion=True, use_default_filename=False)
  File "/usr/local/lib/python3.5/dist-packages/bioblend/galaxy/datasets/__init__.py", line 83, in download_dataset
    raise DatasetStateException("Dataset not ready. Dataset id: %s, current state: %s" % (dataset_id, dataset['state']))
bioblend.galaxy.datasets.DatasetStateException: 'Dataset not ready. Dataset id: f7d140526463f6e7, current state: error'

2017-05-16 16:26:09,133 - INFO - [Elapsed time: 2305.94] [Warning] AutoSNVPhyl had a problem, continuing redmine api anyways.
2017-05-16 16:26:09,134 - INFO - [Elapsed time: 2305.94] [AutoSNVPhyl Error Dump]
Traceback (most recent call last):
  File "/home/devon/PycharmProjects/auto-SNVPhyl/server_runner.py", line 151, in run_snvphyl
    result_path = runner.run()
  File "/home/devon/PycharmProjects/auto-SNVPhyl/main.py", line 41, in run
    return self.main()  # Return the path to the results zip
  File "/home/devon/PycharmProjects/auto-SNVPhyl/main.py", line 173, in main
    wait_for_completion=True, use_default_filename=False)
  File "/usr/local/lib/python3.5/dist-packages/bioblend/galaxy/datasets/__init__.py", line 83, in download_dataset
    raise DatasetStateException("Dataset not ready. Dataset id: %s, current state: %s" % (dataset_id, dataset['state']))
bioblend.galaxy.datasets.DatasetStateException: 'Dataset not ready. Dataset id: f7d140526463f6e7, current state: error'

2017-05-16 16:26:09,134 - INFO - [Elapsed time: 2305.94] Sending GET request to http://redmine.biodiversity.agr.gc.ca/issues/8818.json
2017-05-16 16:26:09,246 - INFO - [Elapsed time: 2306.05] Sending PUT request to http://redmine.biodiversity.agr.gc.ca/issues/8818.json
2017-05-16 16:26:09,840 - INFO - [Elapsed time: 2306.64] Waiting for next check.
