2017-05-29 12:47:32,682 - INFO - [Elapsed time: 0.00] Creating history 8862
2017-05-29 12:47:32,774 - INFO - [Elapsed time: 0.09] 6c322868fc97a6e5
2017-05-29 12:47:32,775 - INFO - [Elapsed time: 0.09] Uploading files to galaxy...
2017-05-29 12:47:32,775 - INFO - [Elapsed time: 0.09] Finding files on the NAS...
2017-05-29 12:47:35,356 - INFO - [Elapsed time: 2.68] Uploading files from the NAS...
2017-05-29 12:47:35,357 - INFO - [Elapsed time: 2.68] 1 of 41: Uploading /mnt/nas/MiSeq_Backup/150203/2014-SEQ-0976_S20_L001_R1_001.fastq.gz
2017-05-29 12:47:35,357 - INFO - [Elapsed time: 2.68] Uploading...
2017-05-29 12:47:43,009 - INFO - [Elapsed time: 10.33] 2 of 41: Uploading /mnt/nas/MiSeq_Backup/150203/2014-SEQ-0976_S20_L001_R2_001.fastq.gz
2017-05-29 12:47:43,009 - INFO - [Elapsed time: 10.33] Uploading...
2017-05-29 12:47:52,715 - INFO - [Elapsed time: 20.03] 3 of 41: Uploading /mnt/nas/MiSeq_Backup/150203/2014-SEQ-0974_S18_L001_R1_001.fastq.gz
2017-05-29 12:47:52,716 - INFO - [Elapsed time: 20.04] Uploading...
2017-05-29 12:48:39,922 - INFO - [Elapsed time: 67.24] 4 of 41: Uploading /mnt/nas/MiSeq_Backup/150203/2014-SEQ-0974_S18_L001_R2_001.fastq.gz
2017-05-29 12:48:39,923 - INFO - [Elapsed time: 67.24] Uploading...
2017-05-29 12:49:10,092 - INFO - [Elapsed time: 97.41] 5 of 41: Uploading /mnt/nas/MiSeq_Backup/150203/2014-SEQ-0977_S21_L001_R1_001.fastq.gz
2017-05-29 12:49:10,092 - INFO - [Elapsed time: 97.41] Uploading...
2017-05-29 12:49:55,494 - INFO - [Elapsed time: 142.81] [Error Dump]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devon/PycharmProjects/auto-SNVPhyl/main.py", line 52, in run
    return self.main()  # Return the path to the results zip
  File "/home/devon/PycharmProjects/auto-SNVPhyl/main.py", line 90, in main
    self.upload_file(file)
  File "/home/devon/PycharmProjects/auto-SNVPhyl/main.py", line 284, in upload_file
    self.gi.tools.upload_file(os.path.join(self.script_dir, "upload", path), self.history_id)
  File "/usr/local/lib/python3.5/dist-packages/bioblend/galaxy/tools/__init__.py", line 149, in upload_file
    return self._tool_post(payload, files_attached=True)
  File "/usr/local/lib/python3.5/dist-packages/bioblend/galaxy/tools/__init__.py", line 219, in _tool_post
    return Client._post(self, payload, files_attached=files_attached)
  File "/usr/local/lib/python3.5/dist-packages/bioblend/galaxy/client.py", line 157, in _post
    files_attached=files_attached)
  File "/usr/local/lib/python3.5/dist-packages/bioblend/galaxyclient.py", line 125, in make_post_request
    verify=self.verify, params=post_params)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt

